Template classes
dbgroup-nagoya-u/hydralist pull request #6
Opened 2022-10-14 04:07 UTC by KoyaMizuno

Key_t→Keyとしてテンプレート化したところに戻しています.
HydraList.h以外のヘッダファイルで多くエラーが出ますが, ご確認のほどよろしくお願い致します.

2022-10-14 04:08 UTC, KoyaMizuno commented
[main] Building folder: hydralist 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/mizuno/hydralist/build/Debug --config Debug --target all --
[build] [2/4  25% :: 1.058] Building CXX object test/CMakeFiles/linked_list_test.dir/linked_list_test.cpp.o
[build] FAILED: test/CMakeFiles/linked_list_test.dir/linked_list_test.cpp.o 
[build] /usr/bin/cmake -E __run_co_compile --tidy=clang-tidy --source=../../test/linked_list_test.cpp -- /usr/bin/g++  -DHYDRALIST_TEST_EXEC_NUM=100000 -DHYDRALIST_TEST_RANDOM_SEED=0 -DHYDRALIST_TEST_THREAD_NUM=8 -DINDEX_FIXTURE_EXEC_NUM_PER_THREAD=100000 -DINDEX_FIXTURE_RANDOM_SEED=0 -DINDEX_FIXTURE_THREAD_NUM=8 -I../../include -I../../external/art -isystem test/googletest-src/googletest/include -isystem test/googletest-src/googletest -g   -Wall -Wextra -mavx512f -mavx512bw -std=gnu++17 -MD -MT test/CMakeFiles/linked_list_test.dir/linked_list_test.cpp.o -MF test/CMakeFiles/linked_list_test.dir/linked_list_test.cpp.o.d -o test/CMakeFiles/linked_list_test.dir/linked_list_test.cpp.o -c ../../test/linked_list_test.cpp
[build] error: too many errors emitted, stopping now [clang-diagnostic-error]
[build] ../../include/hydralist/component/Oplog.h:15:41: error: use of class template 'OpStruct' requires template arguments; argument deduction not allowed in template argument [clang-diagnostic-error]
[build] boost::lockfree::spsc_queue<std::vector<OpStruct *> *, boost::lockfree::capacity<10000>>
[build]                                         ^
[build] ../../include/hydralist/component/common.h:15:7: note: template is declared here
[build] class OpStruct
[build]       ^
[build] ../../include/hydralist/component/Oplog.h:15:53: error: expected a type [clang-diagnostic-error]
[build] boost::lockfree::spsc_queue<std::vector<OpStruct *> *, boost::lockfree::capacity<10000>>
[build]                                                     ^
[build] ../../include/hydralist/component/Oplog.h:26:15: error: use of class template 'OpStruct' requires template arguments; argument deduction not allowed in template argument [clang-diagnostic-error]
[build]   std::vector<OpStruct *> oplog1;
[build]               ^
[build] ../../include/hydralist/component/common.h:15:7: note: template is declared here
[build] class OpStruct
[build]       ^
[build] ../../include/hydralist/component/Oplog.h:27:15: error: use of class template 'OpStruct' requires template arguments; argument deduction not allowed in template argument [clang-diagnostic-error]
[build]   std::vector<OpStruct *> oplog2;
[build]               ^
[build] ../../include/hydralist/component/common.h:15:7: note: template is declared here
[build] class OpStruct
[build]       ^
[build] ../../include/hydralist/component/Oplog.h:28:27: error: use of class template 'OpStruct' requires template arguments; argument deduction not allowed in template argument [clang-diagnostic-error]
[build]   std::vector<std::vector<OpStruct *>> op_{oplog1, oplog2};
[build]                           ^
[build] ../../include/hydralist/component/common.h:15:7: note: template is declared here
[build] class OpStruct
[build]       ^
[build] ../../include/hydralist/component/Oplog.h:28:59: error: expected a type [clang-diagnostic-error]
[build]   std::vector<std::vector<OpStruct *>> op_{oplog1, oplog2};
[build]                                                           ^
[build] ../../include/hydralist/component/Oplog.h:37:5: error: use of undeclared identifier 'op_' [clang-diagnostic-error]
[build]     op_[qnum].clear();
[build]     ^
[build] ../../include/hydralist/component/Oplog.h:40:15: error: use of class template 'OpStruct' requires template arguments; argument deduction not allowed in template argument [clang-diagnostic-error]
[build]   std::vector<OpStruct *> *
[build]               ^
[build] ../../include/hydralist/component/common.h:15:7: note: template is declared here
[build] class OpStruct
[build]       ^
[build] ../../include/hydralist/component/Oplog.h:43:13: error: use of undeclared identifier 'op_' [clang-diagnostic-error]
[build]     return &op_[qnum];
[build]             ^
[build] ../../include/hydralist/component/Oplog.h:60:19: error: 'OpStruct' is not a class, namespace, or enumeration [clang-diagnostic-error]
[build]   enqPerThreadLog(OpStruct::Operation op, Key key, uint8_t hash, void *listNodePtr)
[build]                   ^
[build] ../../include/hydralist/component/common.h:15:7: note: 'OpStruct' declared here
[build] class OpStruct
[build]       ^
[build] ../../include/hydralist/component/Oplog.h:67:7: error: 'OpStruct' is not a class, namespace, or enumeration [clang-diagnostic-error]
[build]   enq(OpStruct::Operation op, Key key, uint8_t hash, void *listNodePtr)
[build]       ^
[build] ../../include/hydralist/component/common.h:15:7: note: 'OpStruct' declared here
[build] class OpStruct
[build]       ^
[build] ../../include/hydralist/component/Oplog.h:69:14: error: cannot form pointer to deduced class template specialization type [clang-diagnostic-error]
[build]     OpStruct *ops = new OpStruct;
[build]              ^
[build] ../../include/hydralist/component/Oplog.h:69:25: error: no viable constructor or deduction guide for deduction of template arguments of 'OpStruct' [clang-diagnostic-error]
[build]     OpStruct *ops = new OpStruct;
[build]                         ^
[build] ../../include/hydralist/component/common.h:15:7: note: candidate template ignored: couldn't infer template argument 'Key'
[build] class OpStruct
[build]       ^
[build] ../../include/hydralist/component/common.h:15:7: note: candidate function template not viable: requires 1 argument, but 0 were provided
[build] ../../include/hydralist/component/Oplog.h:80:5: error: use of undeclared identifier 'op_' [clang-diagnostic-error]
[build]     op_[qnum].push_back(ops);
[build]     ^
[build] ../../include/hydralist/component/Oplog.h:97:10: error: use of class template 'Oplog' requires template arguments; argument deduction not allowed in template argument [clang-diagnostic-error]
[build] std::set<Oplog *> g_perThreadLog;
[build]          ^
[build] ../../include/hydralist/component/Oplog.h:22:7: note: template is declared here
[build] class Oplog
[build]       ^
[build] ../../include/hydralist/component/Oplog.h:100:1: error: 'Oplog' is not a class, namespace, or enumeration [clang-diagnostic-error]
[build] Oplog::getOpLog()
[build] ^
[build] ../../include/hydralist/component/Oplog.h:22:7: note: 'Oplog' declared here
[build] class Oplog
[build]       ^
[build] ../../include/hydralist/component/listNode.h:425:7: error: 'Oplog' is not a class, namespace, or enumeration [clang-diagnostic-error]
[build]       Oplog::enqPerThreadLog(OpStruct::insert, newNode->getMin(), keyHash,
[build]       ^
[build] ../../include/hydralist/component/Oplog.h:22:7: note: 'Oplog' declared here
[build] class Oplog
[build]       ^
[build] ../../include/hydralist/component/listNode.h:425:30: error: 'OpStruct' is not a class, namespace, or enumeration [clang-diagnostic-error]
[build]       Oplog::enqPerThreadLog(OpStruct::insert, newNode->getMin(), keyHash,
[build]                              ^
[build] ../../include/hydralist/component/common.h:15:7: note: 'OpStruct' declared here
[build] class OpStruct
[build]       ^
[build] ../../include/hydralist/component/listNode.h:453:9: error: 'Oplog' is not a class, namespace, or enumeration [clang-diagnostic-error]
[build]         Oplog::enqPerThreadLog(OpStruct::remove, delNode->getMin(), keyHash,
[build]         ^
[build] ../../include/hydralist/component/Oplog.h:22:7: note: 'Oplog' declared here
[build] class Oplog
[build]       ^
[build] 2 warnings and 20 errors generated.
[build] Error while processing /home/mizuno/hydralist/build/Debug/../../test/linked_list_test.cpp.
[build] Suppressed 2 warnings (2 in non-user code).
[build] Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
[build] Found compiler error(s).
[ [...]

2022-10-14 07:05 UTC, baycedar reviewed
とりあえずこの[commit](https://github.com/dbgroup-nagoya-u/hydralist/pull/6/commits/eff884cd25544923b337a4680d8e3b7a7256fdc4)で`listNode.h`を修正してみました．各クラス内でテンプレート化した他クラスのエイリアスを定義して，エラーが吐かれている箇所を置き換えてあげればある程度のエラーは解消できそうな気がします．こちらを参考に少し修正を加えてみてもらえますか？

2022-11-09 02:46 UTC, KoyaMizuno commented
最新版をpushしました.
ご確認のほどよろしくお願いいたします.

2022-11-09 02:47 UTC, KoyaMizuno commented
[main] Building folder: hydralist 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/mizuno/hydralist/build/Debug --config Debug --target all --
[build] [1/2  50% :: 5.467] Building CXX object test/CMakeFiles/hydralist_test.dir/hydralist_test.cpp.o
[build] FAILED: test/CMakeFiles/hydralist_test.dir/hydralist_test.cpp.o 
[build] /usr/bin/cmake -E __run_co_compile --tidy=clang-tidy --source=../../test/hydralist_test.cpp -- /usr/bin/g++  -DHYDRALIST_TEST_EXEC_NUM=100000 -DHYDRALIST_TEST_RANDOM_SEED=0 -DHYDRALIST_TEST_THREAD_NUM=8 -DINDEX_FIXTURE_EXEC_NUM_PER_THREAD=100000 -DINDEX_FIXTURE_RANDOM_SEED=0 -DINDEX_FIXTURE_THREAD_NUM=8 -I../../include -I../../external/art -isystem test/googletest-src/googletest/include -isystem test/googletest-src/googletest -g   -Wall -Wextra -mavx512f -mavx512bw -std=gnu++17 -MD -MT test/CMakeFiles/hydralist_test.dir/hydralist_test.cpp.o -MF test/CMakeFiles/hydralist_test.dir/hydralist_test.cpp.o.d -o test/CMakeFiles/hydralist_test.dir/hydralist_test.cpp.o -c ../../test/hydralist_test.cpp
[build] ../../external/art/Key.h:32:3: warning: 1 uninitialized field at the end of the constructor call [clang-analyzer-optin.cplusplus.UninitializedObject]
[build]   Key() {}
[build]   ^
[build] ../../external/art/Key.h:18:12: note: uninitialized pointer 'this->data'
[build]   uint8_t *data;
[build]            ^
[build] /home/mizuno/hydralist/build/Debug/../../test/hydralist_test.cpp:69:3: note: Control jumps to 'case 0:'  at line 69
[build]   ASSERT_EQ(true, hl.insert(10, 10));
[build]   ^
[build] test/googletest-src/googletest/include/gtest/gtest.h:1889:31: note: expanded from macro 'ASSERT_EQ'
[build] #define ASSERT_EQ(val1, val2) GTEST_ASSERT_EQ(val1, val2)
[build]                               ^
[build] test/googletest-src/googletest/include/gtest/gtest.h:1873:3: note: expanded from macro 'GTEST_ASSERT_EQ'
[build]   ASSERT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)
[build]   ^
[build] test/googletest-src/googletest/include/gtest/gtest_pred_impl.h:148:3: note: expanded from macro 'ASSERT_PRED_FORMAT2'
[build]   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
[build]   ^
[build] test/googletest-src/googletest/include/gtest/gtest_pred_impl.h:134:3: note: expanded from macro 'GTEST_PRED_FORMAT2_'
[build]   GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), on_failure)
[build]   ^
[build] test/googletest-src/googletest/include/gtest/gtest_pred_impl.h:78:3: note: expanded from macro 'GTEST_ASSERT_'
[build]   GTEST_AMBIGUOUS_ELSE_BLOCKER_                                 \
[build]   ^
[build] test/googletest-src/googletest/include/gtest/internal/gtest-port.h:640:3: note: expanded from macro 'GTEST_AMBIGUOUS_ELSE_BLOCKER_'
[build]   switch (0)                          \
[build]   ^
[build] /home/mizuno/hydralist/build/Debug/../../test/hydralist_test.cpp:69:19: note: Calling 'HydraList::insert'
[build]   ASSERT_EQ(true, hl.insert(10, 10));
[build]                   ^
[build] test/googletest-src/googletest/include/gtest/gtest.h:1889:53: note: expanded from macro 'ASSERT_EQ'
[build] #define ASSERT_EQ(val1, val2) GTEST_ASSERT_EQ(val1, val2)
[build]                                                     ^
[build] test/googletest-src/googletest/include/gtest/gtest.h:1873:69: note: expanded from macro 'GTEST_ASSERT_EQ'
[build]   ASSERT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)
[build]                                                                     ^
[build] test/googletest-src/googletest/include/gtest/gtest_pred_impl.h:148:40: note: expanded from macro 'ASSERT_PRED_FORMAT2'
[build]   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
[build]                                        ^
[build] test/googletest-src/googletest/include/gtest/gtest_pred_impl.h:134:43: note: expanded from macro 'GTEST_PRED_FORMAT2_'
[build]   GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), on_failure)
[build]                                           ^
[build] test/googletest-src/googletest/include/gtest/gtest_pred_impl.h:79:52: note: expanded from macro 'GTEST_ASSERT_'
[build]   if (const ::testing::AssertionResult gtest_ar = (expression)) \
[build]                                                    ^
[build] ../../include/hydralist/HydraList.h:28:12: note: Calling 'HydraListImpl::insert'
[build]     return hl->insert(key, val);
[build]            ^
[build] ../../include/hydralist/component/HydraListImpl.h:171:16: note: Calling 'HydraListImpl::getJumpNode'
[build]     jumpNode = getJumpNode(key);
[build]                ^
[build] ../../include/hydralist/component/HydraListImpl.h:116:5: note: Taking false branch
[build]     if (sl.isEmpty()) return dl.getHead();
[build]     ^
[build] ../../include/hydralist/component/HydraListImpl.h:117:53: note: Calling 'ArtRowexIndex::lookup'
[build]     auto *jumpNode = reinterpret_cast<ListNode_t *>(sl.lookup(key));
[build]                                                     ^
[build] ../../include/hydralist/component/SearchLayer.h:97:9: note: Assuming 'key' is > field 'curMin'
[build]     if (key <= curMin) return nullptr;
[build]         ^
[build] ../../include/hydralist/component/SearchLayer.h:97:5: note: Taking false branch
[build]     if (key <= curMin) return nullptr;
[build]     ^
[build] ../../include/hydralist/component/SearchLayer.h:99:9: note: Calling default constructor for 'Key'
[build]     Key endKey;
[build]         ^
[build] ../../external/art/Key.h:32:3: note: 1 uninitialized field at the end of the constructor call
[build]   Key() {}
[build]   ^
[build] ../../include/hydralist/component/HydraListImpl.h:256:5: warning: Undefined or garbage value returned to caller [clang-analyzer-core.uninitialized.UndefReturn]
[build]     return val;
[build]     ^
[build] /home/mizuno/hydralist/build/Debug/../../test/hydralist_test.cpp:69:3: note: Control jumps to 'case 0:'  at line 69
[build]   ASSERT_EQ(true, hl.insert(10, 10));
[build]   ^
[build] test/googletest-src/googletest/include/gtest/gtest.h:1889:31: note: expanded from macro 'ASSERT_EQ'
[build] #define ASSERT_EQ(val1, val2) GTEST_ASSERT_EQ(val1, val2)
[build]                               ^
[build] test/googletest-src/googletest/include/gtest/gtest.h:1873:3: note: expanded from macro 'GTEST_ASSERT_EQ'
[build]   ASSERT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)
[build]   ^
[build] test/googletest-src/googletest/include/gtest/gtest_pred_impl.h:148:3: note: expanded from macro 'ASSERT_PRED_FORMAT2'
[build]   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
[build]   ^
[build] test/googletest-src/googletest/include/gtest/gtest_pred_impl.h:134:3: note: expanded from macro 'GTEST_PRED_FORMAT2_'
[build]   GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), on_failure)
[build]   ^
[build] test/googletest-src/googletest/include/gtest/gtest_pred_impl.h:78:3: note: expanded from macro 'GTEST_ASSERT_'
[build]   GTEST_AMBIGUOUS_ELSE_BLOCKER_                                 \
[build]   ^
[build] test/googletest-src/googletest/include/gtest/internal/gtest-port.h:640:3: note: expanded from macro 'GTEST_AMBIGUOUS_ELSE_BLOCKER_'
[build]   switch (0)                          \
[build]   ^
[build] /home/mizuno/hydralist/build/Debug/../../test/hydralist_test.cpp:69:3: note: Assuming the condition is true
[build]   ASSERT_EQ(true, hl.insert(10, 10));
[build]   ^
[build] test/googletest-src/googletest/include/gtest/gtest.h:1889:31: note: expanded from macro 'ASSERT_EQ'
[build] #define ASSERT_EQ(val1, val2) GTEST_ASSERT_EQ(val1, val2)
[build]                               ^
[build] test/googletest-src/googletest/include/gtest/gtest.h:1873:3: note: expanded from macro 'GTEST_ASSERT_EQ'
[build]   ASSERT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)
[build]   ^
[build] test/googletest-src/googletest/include/gtest/gtest_pred_impl.h:148:3: note: expanded from macro 'ASSERT_PRED_FORMAT2'
[build]   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
[build [...]

2022-11-11 01:41 UTC, baycedar commented
すみませんちょっと遅れましたが見ました．結論から言うと，単に`g_WorkerThreadInst`の宣言位置がおかしかっただけです．`g_WorkerThreadInst`はグローバル変数でかつこれを利用するヘッダは必ず先に`WorkerThread.hpp`をインクルードしているので，`WorkerThread.hpp`の末尾で普通に宣言するだけでOKなのですが，なぜかちゃんとした宣言が`HydraListImpl.hpp`の方に行っていました．なので，[こんな感じ](https://github.com/dbgroup-nagoya-u/hydralist/pull/6/commits/64605db47117378c5f766db75c75ddfdcfac3023)で宣言位置を移動してあげるだけでOKです．

なお，こんな風にissueやPRをもらってもすぐに確認できるわけではないので，投げるのは早め早めにしてもらって問題ありません．とりあえず投げてから色々調べてもらって，こちらが回答する前に解決できたら自己解決しましたと報告してもらえればそれでOKです．目安としては以下の感じですね．

1. 10分ほど悩んでかつ進展が見込めないなら相談の準備を始める．
2. 相談の準備は同じく10分程度を目安に，取り組んでいる作業の目的・起きている問題・取り組んだ作業を列挙する．
3. 同じく10分程度を目安に，2.で列挙した内容をissueないしdraft PRとして文章でまとめ，mention付きで投げる．

2022-11-11 01:56 UTC, KoyaMizuno commented
ご対応ありがとうございます.  修正点をチェックし,  引き続き作業いたします.

また,  相談の対応について承知しました.  自己解決を目指しつつも進展がない状況が多々ありましたので,  考え方・やり方を改めたいと思います.
今後ともよろしくお願いいたします.

2022-11-11 02:45 UTC, KoyaMizuno commented
テストコード (hydralist_test, linked_list_test)をテンプレ化してテストできることを確認しました. 
ご確認のほどよろしくお願いいたします.

2022-11-11 03:43 UTC, baycedar requested changes
はい，ありがとうございます．いくつかコメントを入れたので確認と修正をお願いします．

2022-11-11 03:43 UTC, baycedar commented on include/hydralist/component/Combiner.h
> +      unsigned long logDoneCount = g_WorkerThreadInst<K>[i] -> getLogDoneCount();
`g_WorkerThreadInst<K>`も先頭で`g_WorkerThreadInst_t`としてエイリアスを宣言してもらえますか？

2022-11-11 03:43 UTC, baycedar commented on include/hydralist/component/Oplog.h
> +boost::lockfree::spsc_queue<std::vector<OpStruct<uint64_t> *> *, boost::lockfree::capacity<10000>>
ここの`uint64_t`はただの非負整数ですかね？雰囲気的に`Key_t`っぽいですが，ちょっと確認してみてもらえますか？

2022-11-11 03:43 UTC, baycedar commented on include/hydralist/component/Oplog.h
> +std::set<Oplog<uint64_t> *> g_perThreadLog;
こちらも同上です．

2022-11-11 03:43 UTC, baycedar commented on test/CMakeLists.txt
> +  # )
これは削除でOKです．

2022-11-11 03:43 UTC, baycedar commented on include/hydralist/component/HydraListImpl.h
> +// void pinThread(std::thread *t, int numaId);
この辺りも消してOKです．基本的に過去のコードはコミットログから復元すればよいので，不要になったコードは基本的に削除していってください．

2022-11-11 03:43 UTC, baycedar commented on include/hydralist/component/HydraListImpl.h
> +  };
関数の末尾にはセミコロンは不要なはずですが，なにかエラーや警告が出たりしましたか？

2022-11-11 03:43 UTC, baycedar commented on include/hydralist/component/HydraListImpl.h
> +    g_perNumaSlPtr<K>.resize(totalNumaActive);
このあたりもエイリアスを作成してあげてください．

2022-11-11 03:43 UTC, baycedar commented on include/hydralist/component/HydraListImpl.h
> +// template <class K>
この辺も全削除でOKです．

2022-11-11 05:40 UTC, KoyaMizuno commented on include/hydralist/component/Combiner.h
> +      unsigned long logDoneCount = g_WorkerThreadInst<K>[i] -> getLogDoneCount();
g_WorkerThreadInst_tとエイリアスにしたところエラーが出ています. 
解消のため対応中です.

2022-11-11 05:41 UTC, KoyaMizuno commented on include/hydralist/component/Oplog.h
> +boost::lockfree::spsc_queue<std::vector<OpStruct<uint64_t> *> *, boost::lockfree::capacity<10000>>
ここはテンプレート変数であるべきでしたので修正しました.

2022-11-11 05:42 UTC, KoyaMizuno commented on include/hydralist/component/Oplog.h
> +std::set<Oplog<uint64_t> *> g_perThreadLog;
同じくテンプレート変数としました.

2022-11-11 05:42 UTC, KoyaMizuno commented on test/CMakeLists.txt
> +  # )
削除しました.

2022-11-11 05:43 UTC, KoyaMizuno commented on include/hydralist/component/HydraListImpl.h
> +// void pinThread(std::thread *t, int numaId);
削除しました.
(元からのコメントアウトに関しては念のためそのままにしてあります.)

2022-11-11 05:43 UTC, KoyaMizuno commented on include/hydralist/component/HydraListImpl.h
> +  };
どちらでもエラー,  警告がでませんでしたので,  セミコロンを削除しました.

2022-11-11 05:44 UTC, KoyaMizuno commented on include/hydralist/component/HydraListImpl.h
> +    g_perNumaSlPtr<K>.resize(totalNumaActive);
ここもg_WorkerThreadInst同様のエラーが出ますので対応中です.

2022-11-11 05:45 UTC, KoyaMizuno commented on include/hydralist/component/HydraListImpl.h
> +// template <class K>
削除しました.

2022-11-11 05:45 UTC, baycedar commented on include/hydralist/component/HydraListImpl.h
> +// void pinThread(std::thread *t, int numaId);
あぁ，元からコメントアウトしてあるやつもあるんでしたっけ…．元ソースを参照すればよいので，そちらも削除してしまいましょうか．

2022-11-11 05:47 UTC, baycedar commented on include/hydralist/component/Oplog.h
> +boost::lockfree::spsc_queue<std::vector<OpStruct<uint64_t> *> *, boost::lockfree::capacity<10000>>
ここって単純にテンプレート化すると型の具体化ができなさそうなんですが，その辺りは大丈夫ですか？

2022-11-11 05:56 UTC, KoyaMizuno commented on include/hydralist/component/Oplog.h
> +boost::lockfree::spsc_queue<std::vector<OpStruct<uint64_t> *> *, boost::lockfree::capacity<10000>>
その辺りのエラーは出てないようにみえますが,  上記エラーとの関わり含めてもう少し調べてみます.

2022-11-15 01:31 UTC, KoyaMizuno commented on include/hydralist/component/Combiner.h
> +      unsigned long logDoneCount = g_WorkerThreadInst<K>[i] -> getLogDoneCount();
`g_WorkerThreadInst`が型でないため,  `using g_WorkerThreadInst_t = g_WorkerThreadInst<K>`とできないみたいです.
一旦`g_WorkerThreadInst<K>`のままで残しています.

2022-11-15 01:33 UTC, KoyaMizuno commented on include/hydralist/component/HydraListImpl.h
> +    g_perNumaSlPtr<K>.resize(totalNumaActive);
g_WorkerThreadInst同様で`g_perNumaSlPtr<K>`で残しています.

2022-11-15 01:40 UTC, baycedar commented on include/hydralist/component/Combiner.h
> +      unsigned long logDoneCount = g_WorkerThreadInst<K>[i] -> getLogDoneCount();
変数をテンプレート化…？と思いましたがC++14で[変数テンプレート](https://cpprefjp.github.io/lang/cpp14/variable_templates.html)が追加されてたんですね．この機能を使ったライブラリは頻繁に利用してますが，コーディングで機能自体を利用するのは初めてです[^1]．ひとまず，そういうことであればここはこのままでOKです．

[^1]: HydraListの実装をそこまで理解していませんが，おそらく，そもそもこんな複雑なものを使わないでもいい設計はいくらでもある気はします．

2022-11-15 01:41 UTC, baycedar commented on include/hydralist/component/HydraListImpl.h
> +    g_perNumaSlPtr<K>.resize(totalNumaActive);
こちらも同様にOKです，

2022-11-15 01:42 UTC, baycedar commented on include/hydralist/component/Oplog.h
> +boost::lockfree::spsc_queue<std::vector<OpStruct<uint64_t> *> *, boost::lockfree::capacity<10000>>
ここもどうなるんだろうと思ってましたが，変数テンプレートとなるなら通りそうですね．

2022-11-15 01:50 UTC, KoyaMizuno commented
コメントありがとうございます.
上記時点で区切りがついていますが,   mainにマージ可能でしょうか？
ご確認のほどよろしくお願いいたします.

2022-11-15 05:14 UTC, baycedar commented
すみません気づいていませんでした．元ソースでコメントアウトされてた部分も一旦消してもらえますか？必要になったら元リポジトリを参照するようにしましょう．

2022-11-15 05:41 UTC, KoyaMizuno commented
修正しました. 
コミットしてプッシュしたところ,  以下のエラーとなります.
権限の書き込み権限について確認していただけますでしょうか？

`Missing or invalid credentials.
Error: connect ECONNREFUSED /run/user/2027/vscode-git-03de87c87a.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/run/user/2027/vscode-git-03de87c87a.sock'
}
Missing or invalid credentials.
Error: connect ECONNREFUSED /run/user/2027/vscode-git-03de87c87a.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/run/user/2027/vscode-git-03de87c87a.sock'
}
remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/dbgroup-nagoya-u/hydralist.git/'`

2022-11-15 05:54 UTC, baycedar commented
権限は付与したままです．今までも書けていたはずなので，GitHub側での一時的なエラーか，ローカルの設定の問題のような気がします．

2022-11-15 06:02 UTC, KoyaMizuno commented
ありがとうございます.  対応調べてみます.

2022-11-15 06:07 UTC, KoyaMizuno commented
vscodeウィンドウ再立ち上げしてpushできるようになりました (理由はよくわかりませんが..)
最新版のご確認,  よろしくお願いいたします.

2022-11-15 07:18 UTC, baycedar approved these changes
はい，OKです．一旦これでマージしてください．

次ですが，`Key`と同様に`Value`もテンプレート化したいのですがその前に，ひとまずテストで使用する型を増やしてみてもらえますか？今は`uint64_t`だけだと思いますが，試しに`uint32_t`などを追加して正常に動作するか確認してみてください．

2022-11-15 07:28 UTC, merged

2022-11-15 07:38 UTC, KoyaMizuno commented
マージしました. 
uint32_t追加するとエラーでてしまいますね..
原因調査いたします.